### ISSUE TITLE
Request an arm image for mysql5.7

### ISSUE THREAD

**Issue by annguyen-dev** [docker-library/mysql#978] opened 2023-06-30 02:43 UTC
### Need an arm mysql5.7 image
Currently, our company running mysql5.7. It's running fine on the server, but for the dev team, most of the new members using Apple silicon Mac to work, so the performance of MySQL 5.7 on the m1 chip Mac is really slow.
Our services built on the database are too much, and would take a lot of time to update if we upgrade the MySQL server to 8

**Comment by tianon** [comment] 2023-06-30 22:10
Unfortunately, Oracle's builds for arm64 are only available on MySQL 8+ (and those are what we package in this image).

**Comment by yosifkit** [comment] 2023-06-30 22:19
Duplicate of https://github.com/docker-library/mysql/issues/905

It's only `mysql:8-oracle` that supports `arm64v8`.

**Closed by yosifkit** 2023-06-30 22:19 UTC
