### ISSUE TITLE
Add ARM build to hub

### ISSUE THREAD

**Issue by Niraj-Kamdar** [docker-library/mysql#789] opened 2021-09-28 15:14 UTC
Currently there isn't an ARM build available on docker hub.
```
❯ docker pull mysql:8.0
8.0: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by yosifkit** [comment] 2021-09-28 23:23
Duplicate of https://github.com/docker-library/mysql/issues/318

**Closed by yosifkit** 2021-09-28 23:23 UTC
