### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by bjaspire** [docker-library/mysql#698] opened 2020-08-03 07:14 UTC
I run this command 
`docker pull mysql`

Output is like this:

```
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by tianon** [comment] 2020-08-03 13:54
This is a duplicate of #318

**Closed by tianon** 2020-08-03 13:54 UTC
