### ISSUE TITLE
mysql 5.7 linux/arm64/v8 image 

### ISSUE THREAD

**Issue by croRazor6014** [docker-library/mysql#905] opened 2022-08-08 15:44 UTC
A basic image for apple silicon should be supported.

**Comment by wglambert** [comment] 2022-08-08 18:13
Duplicate of https://github.com/docker-library/mysql/issues/778

**Comment by croRazor6014** [comment] 2022-08-08 18:22
the #778 ticket is similar but is resolved by any mysql build that is on linux/arm64/v8, however no mysql:5.7 build for platform linux/arm64/v8 exists

**Comment by wglambert** [comment] 2022-08-08 18:28
https://github.com/docker-library/mysql/pull/680#issuecomment-1044511070
>Oracle only publishes arm packages for 8.0, and only for OracleLinux.

**Closed** 2022-08-08 23:22 UTC
Labels: Request

**Comment by liskin** [comment] 2022-08-11 17:22
Is there a reason why the Debian variants are only built for amd64?

**Comment by tianon** [comment] 2022-08-11 17:30
> [#680 (comment)](https://github.com/docker-library/mysql/pull/680#issuecomment-1044511070)
> 
> > Oracle only publishes arm packages for 8.0, and only for OracleLinux.

**Comment by tianon** [comment] 2022-08-11 17:30
(In other words, that's not a question we can answer as we don't build them :sweat_smile:)

**Comment by liskin** [comment] 2022-08-11 20:28
Oh I see, even Dockerfile.debian uses mysql packages from Oracle rather than packages from Debian. That indeed explains why it's not built for arm64. A debian-debian variant that uses both debian as a distro and as a source for the mysql-server package would be a useful addition, then. :-)

**Comment by yosifkit** [comment] 2022-08-11 20:47
For these images we try to be as close to upstream releases as possible, so we use the Oracle-provided packages.

Also, Debian replaced the MySQL package with MariaDB back in the `stretch` release (2017), so we can't even get it from Debian packages (https://wiki.debian.org/MySql, https://packages.debian.org/stretch/default-mysql-server).
