### ISSUE TITLE
Allow running mysql_upgrade after database booted

### ISSUE THREAD

**Issue by zedtux** [docker-library/mysql#608] opened 2019-11-18 16:32 UTC
When importing data from an older version of MySQL, this image should have an option, like `MYSQL_UPGRADE` in order to execute `mysql_upgrade --version-check` right after the data has been imported.
Also this `MYSQL_UPGRADE` variable could be set to `force` so that the `--force` flag is passed to `mysql_upgrade`.

I read from #592 that MySQL 8.0.16 and newer doesn't need this anymore, so a version check should also be used in order to run the upgrade for the right versions.

**Comment by tianon** [comment] 2019-11-28 00:31
Duplicate of #130

**Closed by tianon** 2019-11-28 00:31 UTC
Labels: Request

**Comment by zedtux** [comment] 2019-11-28 04:58
Duplicate ... not 100% but whatever.
