### ISSUE TITLE
Setting MYSQL_ALLOW_EMPTY_PASSWORD doesn't have any effect on  5.7

### ISSUE THREAD

**Issue by razcakappa** [docker-library/mysql#494] opened 2018-09-25 13:00 UTC
I noticed that setting `MYSQL_ALLOW_EMPTY_PASSWORD` to `true` doesn't make any effect. Then checked the `docker-entrypoint.sh` too and saw there's nothing related to this variable when its `true`. 

Is this deprecated intentionally due to the fact of Mysql 5.7 officially doen't support the feature?
How others get around with this?

**Comment by tianon** [comment] 2018-09-26 00:47
It is referenced here:

https://github.com/docker-library/mysql/blob/b39f1e5e4ec82dc8039cecc91dbf34f6c9ae5fb0/5.7/docker-entrypoint.sh#L100

I can't reproduce an issue:

```console
$ docker pull mysql:5.7
5.7: Pulling from library/mysql
Digest: sha256:1d8f471c7e2929ee1e2bfbc1d16fc8afccd2e070afed24805487e726ce601a6d
Status: Image is up to date for mysql:5.7

$ docker run -it --rm -e MYSQL_ALLOW_EMPTY_PASSWORD=1 mysql:5.7
Initializing database
2018-09-26T00:46:13.367983Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-09-26T00:46:13.672061Z 0 [Warning] InnoDB: New log files created, LSN=45790
2018-09-26T00:46:13.741008Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2018-09-26T00:46:13.750480Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 91b7fb50-c125-11e8-b5a1-0242ac120018.
2018-09-26T00:46:13.752123Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2018-09-26T00:46:13.752877Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2018-09-26T00:46:14.401369Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401389Z 1 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401396Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401406Z 1 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401409Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401418Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401441Z 1 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:14.401448Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
Database initialized
Initializing certificates
Generating a 2048 bit RSA private key
.....+++
...................+++
unable to write 'random state'
writing new private key to 'ca-key.pem'
-----
Generating a 2048 bit RSA private key
.........................+++
..............................+++
unable to write 'random state'
writing new private key to 'server-key.pem'
-----
Generating a 2048 bit RSA private key
.....+++
....................................................+++
unable to write 'random state'
writing new private key to 'client-key.pem'
-----
Certificates initialized
MySQL init process in progress...
2018-09-26T00:46:16.632370Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-09-26T00:46:16.633232Z 0 [Note] mysqld (mysqld 5.7.23) starting as process 92 ...
2018-09-26T00:46:16.634761Z 0 [Note] InnoDB: PUNCH HOLE support available
2018-09-26T00:46:16.634772Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-09-26T00:46:16.634774Z 0 [Note] InnoDB: Uses event mutexes
2018-09-26T00:46:16.634776Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-09-26T00:46:16.634778Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2018-09-26T00:46:16.634780Z 0 [Note] InnoDB: Using Linux native AIO
2018-09-26T00:46:16.634896Z 0 [Note] InnoDB: Number of pools: 1
2018-09-26T00:46:16.634946Z 0 [Note] InnoDB: Using CPU crc32 instructions
2018-09-26T00:46:16.635870Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-09-26T00:46:16.639901Z 0 [Note] InnoDB: Completed initialization of buffer pool
2018-09-26T00:46:16.641032Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-09-26T00:46:16.651844Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2018-09-26T00:46:16.656534Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-09-26T00:46:16.656603Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-09-26T00:46:16.683149Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-09-26T00:46:16.685229Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2018-09-26T00:46:16.685259Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2018-09-26T00:46:16.686618Z 0 [Note] InnoDB: 5.7.23 started; log sequence number 2588944
2018-09-26T00:46:16.686949Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2018-09-26T00:46:16.687572Z 0 [Note] Plugin 'FEDERATED' is disabled.
2018-09-26T00:46:16.690561Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180926  0:46:16
2018-09-26T00:46:16.700029Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2018-09-26T00:46:16.700675Z 0 [Warning] CA certificate ca.pem is self signed.
2018-09-26T00:46:16.709419Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2018-09-26T00:46:16.712250Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.712315Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.712351Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.712395Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.712412Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.712444Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.716087Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.716128Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:16.728419Z 0 [Note] Event Scheduler: Loaded 0 events
2018-09-26T00:46:16.728748Z 0 [Note] mysqld: ready for connections.
Version: '5.7.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
2018-09-26T00:46:18.500428Z 4 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500443Z 4 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500448Z 4 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500458Z 4 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500461Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500466Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500495Z 4 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:18.500501Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.

2018-09-26T00:46:18.502618Z 0 [Note] Giving 0 client threads a chance to die gracefully
2018-09-26T00:46:18.502631Z 0 [Note] Shutting down slave threads
2018-09-26T00:46:18.502634Z 0 [Note] Forcefully disconnecting 0 remaining clients
2018-09-26T00:46:18.502638Z 0 [Note] Event Scheduler: Purging the queue. 0 events
2018-09-26T00:46:18.502659Z 0 [Note] Binlog end
2018-09-26T00:46:18.502909Z 0 [Note] Shutting down plugin 'ngram'
2018-09-26T00:46:18.502915Z 0 [Note] Shutting down plugin 'partition'
2018-09-26T00:46:18.502919Z 0 [Note] Shutting down plugin 'BLACKHOLE'
2018-09-26T00:46:18.502923Z 0 [Note] Shutting down plugin 'ARCHIVE'
2018-09-26T00:46:18.502926Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2018-09-26T00:46:18.502944Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2018-09-26T00:46:18.502947Z 0 [Note] Shutting down plugin 'MyISAM'
2018-09-26T00:46:18.502952Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2018-09-26T00:46:18.502956Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2018-09-26T00:46:18.502959Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2018-09-26T00:46:18.502962Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2018-09-26T00:46:18.502965Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2018-09-26T00:46:18.502968Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2018-09-26T00:46:18.502972Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2018-09-26T00:46:18.502975Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2018-09-26T00:46:18.502978Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2018-09-26T00:46:18.502982Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2018-09-26T00:46:18.502985Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2018-09-26T00:46:18.502988Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2018-09-26T00:46:18.502991Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2018-09-26T00:46:18.502995Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2018-09-26T00:46:18.502998Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2018-09-26T00:46:18.503002Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2018-09-26T00:46:18.503005Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2018-09-26T00:46:18.503009Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2018-09-26T00:46:18.503012Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2018-09-26T00:46:18.503015Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2018-09-26T00:46:18.503018Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2018-09-26T00:46:18.503022Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2018-09-26T00:46:18.503024Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2018-09-26T00:46:18.503027Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2018-09-26T00:46:18.503030Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2018-09-26T00:46:18.503034Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2018-09-26T00:46:18.503037Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2018-09-26T00:46:18.503041Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2018-09-26T00:46:18.503044Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2018-09-26T00:46:18.503046Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2018-09-26T00:46:18.503049Z 0 [Note] Shutting down plugin 'InnoDB'
2018-09-26T00:46:18.503078Z 0 [Note] InnoDB: FTS optimize thread exiting.
2018-09-26T00:46:18.503136Z 0 [Note] InnoDB: Starting shutdown...
2018-09-26T00:46:18.603454Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2018-09-26T00:46:18.604047Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 180926  0:46:18
2018-09-26T00:46:19.622047Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12359226
2018-09-26T00:46:19.626509Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-09-26T00:46:19.626547Z 0 [Note] Shutting down plugin 'MEMORY'
2018-09-26T00:46:19.626560Z 0 [Note] Shutting down plugin 'CSV'
2018-09-26T00:46:19.626570Z 0 [Note] Shutting down plugin 'sha256_password'
2018-09-26T00:46:19.626584Z 0 [Note] Shutting down plugin 'mysql_native_password'
2018-09-26T00:46:19.627032Z 0 [Note] Shutting down plugin 'binlog'
2018-09-26T00:46:19.628111Z 0 [Note] mysqld: Shutdown complete


MySQL init process done. Ready for start up.

2018-09-26T00:46:19.872028Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-09-26T00:46:19.872848Z 0 [Note] mysqld (mysqld 5.7.23) starting as process 1 ...
2018-09-26T00:46:19.874476Z 0 [Note] InnoDB: PUNCH HOLE support available
2018-09-26T00:46:19.874487Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-09-26T00:46:19.874489Z 0 [Note] InnoDB: Uses event mutexes
2018-09-26T00:46:19.874491Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-09-26T00:46:19.874493Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2018-09-26T00:46:19.874495Z 0 [Note] InnoDB: Using Linux native AIO
2018-09-26T00:46:19.874610Z 0 [Note] InnoDB: Number of pools: 1
2018-09-26T00:46:19.874718Z 0 [Note] InnoDB: Using CPU crc32 instructions
2018-09-26T00:46:19.876141Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-09-26T00:46:19.880455Z 0 [Note] InnoDB: Completed initialization of buffer pool
2018-09-26T00:46:19.881581Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-09-26T00:46:19.894312Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2018-09-26T00:46:19.904142Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-09-26T00:46:19.904216Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-09-26T00:46:19.934398Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-09-26T00:46:19.934939Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2018-09-26T00:46:19.934947Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2018-09-26T00:46:19.935328Z 0 [Note] InnoDB: 5.7.23 started; log sequence number 12359226
2018-09-26T00:46:19.935479Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2018-09-26T00:46:19.935588Z 0 [Note] Plugin 'FEDERATED' is disabled.
2018-09-26T00:46:19.937667Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180926  0:46:19
2018-09-26T00:46:19.938711Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2018-09-26T00:46:19.938882Z 0 [Warning] CA certificate ca.pem is self signed.
2018-09-26T00:46:19.940478Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2018-09-26T00:46:19.940501Z 0 [Note] IPv6 is available.
2018-09-26T00:46:19.940508Z 0 [Note]   - '::' resolves to '::';
2018-09-26T00:46:19.940518Z 0 [Note] Server socket created on IP: '::'.
2018-09-26T00:46:19.941928Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2018-09-26T00:46:19.942663Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.942681Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.942688Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.942703Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.942707Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.942715Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.944112Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.944123Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-09-26T00:46:19.948083Z 0 [Note] Event Scheduler: Loaded 0 events
2018-09-26T00:46:19.948227Z 0 [Note] mysqld: ready for connections.
Version: '5.7.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

**Comment by yosifkit** [comment] 2018-10-02 17:49
Seems to be solved; closing.

**Closed by yosifkit** 2018-10-02 17:49 UTC
Labels: question
