### ISSUE TITLE
ERROR 1396 (HY000): Operation CREATE USER failed for 'root'@'%'

### ISSUE THREAD

**Issue by innovia** [docker-library/mysql#129] opened 2016-01-07 14:41 UTC
we are struggling to figure this one out

it does not work out of the box - running on OSX

everytime we attempt to start it it fails after intializing the db but when we run it a 2nd time mysql runs becuas ethe DATA_DIR folder already exists

why does it keep failing?

running version 5.6.28 of mysql WITHOUT MODIFICATIONS!

also worth mentioning we see the issue only with docker-compose, 

seems like the root user is the one being used to log in to mysql and then attempt to create it while logged in as root fails

**Comment by yosifkit** [comment] 2016-01-08 01:15
I assume this is the entrypoint script in the mysql image that is failing.

Is it the usual way to modify the `root` user in sql while being the `root` user and works fine without `docker-compose`.  What does your yaml have configured for the mysql container?

**Comment by Ninir** [comment] 2016-02-01 14:35
@yosifkit I assume @innovia has this kind of configuration:

```yaml
db:
    image: mysql:5.7.10
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - 3306:3306
```

It is also failing for me, but running `docker-compose up` again makes it.

**Comment by jlaswell** [comment] 2016-02-01 17:56
@Ninir I'm seeing the same for a fresh `docker-compose up` on Ubuntu 14.04 for the `:5.6` tag, and it also works after re-running another `docker-compose up`. It only seems to fail any time after `rm`ing the container, so it seems to be limited to initial creation.

**Comment by yosifkit** [comment] 2016-02-01 23:58
@Ninir, the entrypoint script would fail to work if you set `MYSQL_USER` to `root`; specifically [line #75](https://github.com/docker-library/mysql/blob/2e1fda0b2ca389a9e9d242042e56526a2f08988c/5.7/docker-entrypoint.sh#L75) will fail to create the second user `'root'@'%'` since it will already exist in the users table from [above](https://github.com/docker-library/mysql/blob/2e1fda0b2ca389a9e9d242042e56526a2f08988c/5.7/docker-entrypoint.sh#L53-L63). If you want to use `root` as your user, you only need to set `MYSQL_ROOT_PASSWORD`.

**Comment by Ninir** [comment] 2016-02-02 08:04
@yosifkit I know, was just Reproducing @innovia s case :)

**Comment by tim545** [comment] 2016-03-21 04:43
hey guys, I've also been getting this error, but not with docker compose, by running the container, deleting it and running it again, there's no logical reason to actually do that of course but I ended up doing this while setting up some containers, my simplest solution was to just stop being lazy and not use the root user, so this did _not_ work:

`docker run --name mysql -p 32770:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=root -e MYSQL_PASSWORD=root -d mysql:5.6`

but this _did_ work:

`docker run --name mysql -p 32770:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=myusername -e MYSQL_PASSWORD=mypassword -d mysql:5.6`

**Comment by laggingreflex** [comment] 2016-08-03 01:52
Could this be related to [this docker-compose issue](https://github.com/docker/compose/issues/374)? I.e the mysql isn't yet ready when server tries to access it. I was having the same error and tried a solution from there ([goss](https://github.com/docker/compose/issues/374#issuecomment-237006997)) and it fixed it.

**Comment by ababushkin** [comment] 2016-09-01 01:23
Anyone found a solution to this problem yet? I've had to switch to MariaDB for the time being.

**Comment by Ninir** [comment] 2016-09-01 07:14
@ababushkin One solution was suggested, which is about only setting the `MYSQL_ROOT_PASSWORD` env var. Are you having another issues?

**Comment by ababushkin** [comment] 2016-09-02 04:33
@Ninir sorry I didn't realise that was the suggested solution - I skimmed past @yosifkit post :)

Trying that worked for me.

**Comment by yosifkit** [comment] 2016-09-02 17:04
As far as I can tell, the original issue seems solved and has helped others.  Closing.

**Closed by yosifkit** 2016-09-02 17:04 UTC

**Comment by karthik-aiyer-fujixerox** [comment] 2017-03-15 00:39
@yosifkit I encountered the same problem and tried the suggested solution but doesn't seem to be working for me.
Running **attached** docker file with following command still gives me the error mentioned in attached **docker_log.txt**

Command:
`
docker build --build-arg http_proxy=<value> --build-arg https_proxy=<value> -f mySQL_Dockerfile -t mysql .
`

[docker_log.txt](https://github.com/docker-library/mysql/files/843111/docker_log.txt)
[mySQL_Dockerfile.txt](https://github.com/docker-library/mysql/files/843112/mySQL_Dockerfile.txt)

**Comment by ltangvald** [comment] 2017-03-15 06:49
That is very odd. They are just two different tags for the same image. Both your mysql:latest and mysql:5.7 are updated?

**Comment by ltangvald** [comment] 2017-03-15 06:52
Have you tried deleting your built image to ensure it's rebuilt from scratch? At least in earlier Docker versions I occasionally had issues where changes in the Dockerfile didn't always make the affected layer rebuild properly.

**Comment by helsont** [comment] 2018-03-15 22:02
Hi, is it possible to add a warning log when you specify `MYSQL_USER: root`? I was wrangling with this bug for days before I found this thread. Think it might be useful to add a heads up for people in the future. I don't see this anywhere in the documentation, either. At minimum a note in the docs would be helpful.

**Comment by vivekbarsagadey** [comment] 2019-08-19 12:35
> @yosifkit I assume @innovia has this kind of configuration:
> 
> ```yaml
> db:
>     image: mysql:5.7.10
>     environment:
>         MYSQL_ROOT_PASSWORD: root
>         MYSQL_DATABASE: mydb
>         MYSQL_USER: root
>         MYSQL_PASSWORD: root
>     ports:
>         - 3306:3306
> ```
> 
> It is also failing for me, but running `docker-compose up` again makes it. This seems logical as we try to create another `root` user.

For  mysql:latest, some how   MYSQL_ROOT_HOST:'%'  property is not working, so even if you are using latest, please exclude host
