### ISSUE TITLE
multi-arch mysql image support

### ISSUE THREAD

**Issue by arm64b** [docker-library/mysql#415] opened 2018-04-23 05:34 UTC
Recently I tried to pull a `mysql` image on linux/arm64 system, but seems there's no `arm64` support in the manifest:
```
# docker pull mysql:latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64 in the manifest list entries
```
So can we add `arm64` support in the official mysql manifest?

**Comment by tianon** [comment] 2018-04-23 20:31
Duplicate of https://github.com/docker-library/mysql/issues/318.

**Closed by tianon** 2018-04-23 20:31 UTC
