### ISSUE TITLE
how to reslove arm64/v8

### ISSUE THREAD

**Issue by M1NGc** [docker-library/mysql#657] opened 2020-04-14 02:21 UTC
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by wglambert** [comment] 2020-04-14 15:20
This image doesn't support architectures other than amd64
MariaDB does have an arm64/v8 variant if you'd like https://hub.docker.com/_/mariadb?tab=tags

https://github.com/docker-library/mysql/issues/318#issuecomment-541534820
>My idea for this is to add support for rpm-based images since repo.mysql.com offers rpms for aarch64. This would only be for 8.0, though.

https://github.com/docker-library/mysql/issues/318#issuecomment-541592821
>8.0 was the first version upstream added official arm support for

Closing as duplicate of https://github.com/docker-library/mysql/issues/318

**Closed by wglambert** 2020-04-14 15:20 UTC
