### ISSUE TITLE
Specifying --server-id not working

### ISSUE THREAD

**Issue by simongui** [docker-library/mysql#167] opened 2016-05-12 16:18 UTC
How do I get the docker image to pick up the `--server-id` option?

I'm starting the container with the following:

```
docker run --name foo -v $DIR/my.cnf:/etc/my.cnf -v $DIR/$host:/var/log --hostname $host -e MYSQL_ROOT_PASSWORD=password -p $port:3306 -d mysql/mysql-server:5.7 --server-id=1 > /dev/null 2> /dev/null
```

The server starts up with the following error:
```
2016-05-12T16:08:45.485529Z 0 [ERROR] You have enabled the binary log, but you haven't provided the mandatory server-id. Please refer to the proper server start-up parameters documentation
2016-05-12T16:08:45.485562Z 0 [ERROR] Aborting
```

**Comment by yosifkit** [comment] 2016-05-12 19:01
I cannot reproduce this on the `mysql:5.7` image. This might be due to the differences between the `mysql` images and `mysql/mysql-sever` images.

What is in your `my.cnf`. Here is what I ran:

```console
$ cat my.cnf
[mysqld]
log-bin=foo-bin
$ docker run -d --name mysql -v "$PWD/my.cnf":/etc/my.cnf -v "$PWD/mysql-logs/":/var/log/ --hostname mysql-foo -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7 --server-id=1
```

**Comment by ltangvald** [comment] 2016-05-13 05:29
I've run some tests previously on mysql/mysql-server with binlogging without issue, but I'll see if I can reproduce it.

**Comment by ltangvald** [comment] 2016-05-13 06:16
I can reproduce this on mysql/mysql-server only; 
If log-bin and server-id are both specified in config file or on command line it works.
If log-bin is specified in the config file and server-id on command line it gives the reported error.

The cause is that the Oracle image doesn't correctly use the command line options when temporarily starting the server, only the config file.
I've made an upstream report at http://bugs.mysql.com/bug.php?id=81415, and since this doesn't affect the community image I'll close this report.

**Closed by ltangvald** 2016-05-13 06:16 UTC
