### ISSUE TITLE
Unexplained high memory usage by the MySQL container

### ISSUE THREAD

**Issue by emados** [docker-library/mysql#389] opened 2018-03-06 08:37 UTC
# Explanation
The MySQL container is using a high amount of memory although it's empty and not linked to any other container. In other words, I just start the container and its memory usage will grow over the time until there's not much memory left and it crashes.

## Versions/Specs
  * **Server:** DigitalOcean - 1 GB Memory / 1vCPU / 25 GB Disk / NYC3 - Ubuntu Docker 17.12.0~ce on 16.04
  * **System:** Ubuntu 16.04
  * **Docker:** 17.12.0-ce, build c97c6d6
  * **MySQL Image:** version 5.7.12 image id 2fd136002c22

## Steps to reproduce
  1. Spin up a new droplet using the Docker addon.
  2. Create a config directory and the following config files:

     ```bash
     mkdir -p /root/dckrmysql/config/
     echo -e "[mysqld]\nperformance_schema = 0" > "/root/dckrmysql/config/disable_performance_schema.cnf"
     echo -e "[mysqld]\ncharacter-set-server = utf8\ncollation-server = utf8_general_ci" > "/root/dckrmysql/config/charset_utf8.cnf"
     ```

  3. Run a `mysql:5.7.12` container

     ```bash
     docker run -d -e MYSQL_RANDOM_ROOT_PASSWORD=true -v /root/dckrmysql/config:/etc/mysql/conf.d mysql:5.7.12
     ```

  4. Watch the memory usage of the running container grows over time, although neither there're connection nor actual tables and data.

     ```bash
     watch -dn2 "docker stats --no-stream --format 'table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}'"
     ```

**Update 1**
Memory usage timeline: _(timings and memory usage may not be 100% accurate)_
  * When first launched: ~59MiB / 992.3MiB
  * Less than ~10mins. later: ~204MiB / 992.3MiB
  * About ~8hrs. later: ~702MiB / 992.3MiB
  * About 1hr - 2hrs. later: it crashed

I couldn't keep an accurate timeline of memory usage, but what I believe what I provided gives a clear idea that something is not right with how the container runs.

CPU usage stays almost the same during the lifetime of the container (around 0.04% to 0.06%).

**Comment by tianon** [comment] 2018-05-07 22:14
Apologies for the delay -- there's a decent amount of detail here, but I'm failing to see what makes this a Docker-specific issue?  We use a fairly stock configuration provided by MySQL upstream (from their provided Debian packages, to be specific), so I think any issues with memory usage (for what seems to be an idle container) should probably be taken up in a MySQL-specific forum.

**Comment by wglambert** [comment] 2018-07-17 19:50
Going to close the issue without something explicitly denoting the Docker image as being the cause, without that there's nothing to change in the image to alleviate the issue

**Closed by wglambert** 2018-07-17 19:50 UTC
Labels: Issue
