### ISSUE TITLE
Add HEALTHCHECK entry to Dockerfile to reliably monitor container readiness status

### ISSUE THREAD

**Issue by zarbis** [docker-library/mysql#196] opened 2016-08-01 12:33 UTC
As of Docker release 1.12.0:

> New HEALTHCHECK Dockerfile instruction to support user-defined healthchecks [#23218](https://github.com/docker/docker/pull/23218)

This feature will greatly facilitate start of dependent containers only after mysql container completes initialization, both manually and with Compose (after it becomes healthcheck-aware [compose/#3754](https://github.com/docker/compose/issues/3754)).

**Comment by ltangvald** [comment] 2016-08-02 04:27
Yeah, especially for Compose this sounds excellent!

**Comment by hyleung** [comment] 2016-11-01 21:41
Had a quick stab at this - I have a _partial_ solution I think (https://github.com/hyleung/mysql/commit/8f7fc32ecdc4f244480130ab950bdfcd8bd4045b).

The problem is that the way I've done the health check, it only works if the container is started with `MYSQL_ROOT_PASSWORD`. This happens to be the way I start my containers most of the time, but the other startup options (e.g. `MYSQL_ALLOW_EMPTY_PASSWORD`, etc.) most likely won't work. Anybody have ideas about how to implement a health check with in those situations?

**Comment by tianon** [comment] 2016-11-01 22:45
I think @yosifkit summarized adding `HEALTHCHECK` by default really well over in https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271:

> I do not feel that generalized healthchecks on the official images are really that useful. 
> 
>  - users will have their own idea of what is "healthy"
>  - it does not actually test that the service is listening to connections outside of `localhost` (see https://github.com/docker-library/healthcheck for some examples that do more than what's proposed here, including attempting to check whether the service is listening remotely)
>   - some of the Official Images even purposely start in a `localhost` only mode for database initialization and then kill and start the main service with full network availability
>  - after upgrading their images, current users will have extra unexpected load on their systems for healthchecks they don't necessarily need/want and may be unaware of

(some of that can be abated, such as trying to connect to the external IP of the container instead of `localhost`, but the points about difficult generalization and added load still definitely apply)

**Comment by hyleung** [comment] 2016-11-02 01:51
@tianon ic, makes sense (tho' similar to this [comment](https://github.com/docker-library/cassandra/pull/76#issuecomment-246100794) on the same thread, I'm interested in knowing when the DB is ready so that I can start some integration tests). 

In any case, should this issue be closed then?

**Comment by ltangvald** [comment] 2016-11-02 06:36
I think the definition of "healthy" for a database can be agreed on by most as "ready to accept connections", but from the (very brief) look I had at the system, it doesn't quite fit with the way it's handled in Docker.
It is something that could be very useful for automated systems, and for frameworks like Compose, but we'd need a non-disruptive way of doing it (users who don't need it shouldn't notice it's there, and it can't add significant complexity to the image).
I'd like to keep the issue open for now, and see if we can find a solution.

**Comment by ioggstream** [comment] 2016-11-02 09:54
How will this healtcheck stuff interact with kubernetes and other orchestration engines running on distributed systems?

We aren't goint to trigger anything in case of unhealth, right?

I think it may be usefult but not active by default (eg. we could distribute a healtcheck.sh but leave to the user the choice to enable it).

**Comment by hyleung** [comment] 2016-11-02 16:19
@ioggstream I believe for Kubernetes, the health checks (readiness or liveness probes) are configured in the Podspec file (i.e. not baked into the container image) - http://kubernetes.io/docs/user-guide/liveness/.

**Comment by ioggstream** [comment] 2016-11-02 16:51
@hyleung yes, this kind of checks may interfere with orchestrators (I use openshift/kubernetes) so I'm for providing an "enabler", not to activate them by default.

**Comment by iBobik** [comment] 2017-04-28 13:44
If in Dockerfile will be HEALTHCHECK line will Kubernetes have problem with it? If not, why block this feature because some orchestrator have own solution?

**Comment by josephspurrier** [comment] 2017-05-17 04:30
Here is how to check from docker-compose: http://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready/42757250#42757250

**Comment by L0rD59** [comment] 2017-05-18 07:13
Hi @josephspurrier do you have the same solution when using mounted volume /docker-entrypoint-initdb.d and import big database (i need to wait fully import before start other container)

Thx

**Comment by L0rD59** [comment] 2017-05-18 09:16
I've try this one and works fine : 

```
healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
``` 

Test if mysql command is running (when importing dump from /docker-entrypoint-initdb.d

**Comment by ltangvald** [comment] 2017-05-18 11:22
A fairly robust indication of the server's readiness is the presence of the .sock file, but image initialization will also do a temporary start of the server, so I've considered maybe having the entrypoint script write a simple flag file before the final startup, and having the image's healthcheck command check for both that file and the sock file.

**Comment by iBobik** [comment] 2017-05-18 13:41
> A fairly robust indication of the server's readiness is the presence of the .sock file

Are you sure this socketfile will be removed when server crashed or is not working?

**Comment by ltangvald** [comment] 2017-05-19 06:03
If it crashes (exits) the container will stop, but a hang would break this, yes. Running «mysqladmin ping» should work, though.

**Comment by josephspurrier** [comment] 2017-05-21 16:40
The most reliable way I found is using an actual select query. The ping command will return when the MySQL server is started, but not when it's actually ready to handle queries. If you want to use it for a health check, you'll have to modify it a bit.

while ! mysql -e "select 1" -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD >/dev/null 2>&1; do
    sleep 1
done

**Comment by iBobik** [comment] 2017-05-21 18:13
It seems the best healthcheck script is there: https://github.com/docker-library/healthcheck/blob/master/mysql/docker-healthcheck

Any reason why not just copy it there?

**Comment by tianon** [comment] 2017-12-26 23:15
Closing given that there's not a reliable way we can add this by default to the image, and there are now a decent number of examples for folks to build this for their own uses (matching their own valid assumptions per-environment).

**Closed by tianon** 2017-12-26 23:15 UTC
