### ISSUE TITLE
MySQL 8: SELECT privileges to use JSON_TABLE

### ISSUE THREAD

**Issue by JustGreg** [docker-library/mysql#418] opened 2018-04-26 07:52 UTC
SQL queries with [JSON_TABLE](https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html) prints `ERROR 1142 (42000) SELECT command denied to user 'username'@'localhost' for table 'json_table'`

```
docker run -d -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test --name mysql mysql:8

docker exec -it mysql bash

root@174b7f9be26b:/# mysql -u test -ptest test

mysql> SELECT *
    -> FROM
    ->   JSON_TABLE(
    ->     '[{"x":2,"y":"8"},{"x":"3","y":"7"},{"x":"4","y":6}]',
    ->     "$[*]" COLUMNS(
    ->       xval VARCHAR(100) PATH "$.x",
    ->       yval VARCHAR(100) PATH "$.y"
    ->     )
    ->   ) AS  jt1;
ERROR 1142 (42000): SELECT command denied to user 'test'@'localhost' for table 'json_table'
```
I haven't found a good solution yet without grant privileges to all databases (`grant usage,select on *.* to 'username'@'%';`)

**Comment by ltangvald** [comment] 2018-04-26 11:11
This does look like a bug in the functionality, as I don't think the json_table function should require this access level. If so you may have to use *.* until the issue is fixed upstream

**Comment by ltangvald** [comment] 2018-04-26 11:15
Closing this since it's not an issue with the image, but in MySQL (Upstream will take another look at https://bugs.mysql.com/bug.php?id=90610)

**Closed by ltangvald** 2018-04-26 11:15 UTC
