### ISSUE TITLE
Failed to access directory for --secure-file-priv 

### ISSUE THREAD

**Issue by sharonsahadevan** [docker-library/mysql#540] opened 2019-02-13 17:36 UTC
Hi,

when I started the container using docker-compose up, I am getting below error.

_**_Attaching to mysql
mysql    | 
mysql    | ERROR: mysqld failed while attempting to check config
mysql    | command was: "mysqld --verbose --help"
mysql    | 
mysql    | mysqld: Error on realpath() on '/var/lib/mysql-files' (Error 2 - No such file or directory)
mysql    | 2019-02-13T17:30:55.780793Z 0 [ERROR] [MY-010095] [Server] Failed to access directory for --secure-file-priv. Please make sure that directory exists and is accessible by MySQL Server. Supplied value : /var/lib/mysql-files
mysql    | 2019-02-13T17:30:55.786696Z 0 [ERROR] [MY-010119] [Server] Aborting_**_

my object is mapping my.cnf file to host directory so I can able to do the changes easily and changes will be persisted. I used official mysql image.

please guide me on how to solve this issue using docker-compose method.

docker compose file:
===============
version: '3.3'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: cdr
      MYSQL_PASSWORD: secret123

**Comment by wglambert** [comment] 2019-02-13 17:51
Duplicate of https://github.com/docker-library/mysql/issues/541

**Closed by wglambert** 2019-02-13 17:51 UTC
