### ISSUE TITLE
mysql version 8.0.33 linux arm64/v8 build faild

### ISSUE THREAD

**Issue by BearDare** [docker-library/mysql#969] opened 2023-04-25 03:51 UTC
I have a problem during the build，the build log is as follows, It seems that the mysql package cannot be downloaded through apt-install，how to solve it 
```
E: Unable to locate package mysql-community-client
E: Unable to locate package mysql-community-server-core
The command '/bin/sh -c {                 echo mysql-community-server mysql-community-server/data-dir select '';                 
echo mysql-community-server mysql-community-server/root-pass password '';                 
echo mysql-community-server mysql-community-server/re-root-pass password '';                 
echo mysql-community-server mysql-community-server/remove-test-db select false; } | debconf-set-selections         
&& apt-get update         && apt-get install -y                 mysql-community-client="${MYSQL_VERSION}"                 mysql-community-server-core="${MYSQL_VERSION}"         
&& rm -rf /var/lib/apt/lists/*         
&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld        
&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld         
&& chmod 1777 /var/run/mysqld /var/lib/mysql' returned a non-zero code: 100
```

**Comment by tianon** [comment] 2023-04-25 20:58
Duplicate of #953 - Oracle only supports arm64 on Oracle Linux (not Debian)

**Closed by tianon** 2023-04-25 20:58 UTC
