### ISSUE TITLE
change log behavior when SYS_NICE capabilities are not available

### ISSUE THREAD

**Issue by alexander-haller** [docker-library/mysql#779] opened 2021-07-19 10:12 UTC
Without CAP_SYS_NICE privileges, MySQL 8 will spam the log with
"mbind: Operation not permitted" errors.
Ideally MySQL will warn once at the start and then be silent about this.

see also https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log

**Comment by wglambert** [comment] 2021-07-19 16:24
https://github.com/docker-library/mysql/issues/303#issuecomment-409047241
>. . . there's not a bug here we can fix. The mbind message is a warning. It is harmless, and should not cause any issues except performance. If you wish to remove it, you'll need to tweak your container's seccomp profile to allow NUMA, and there's literally nothing we can do about that from inside the image -- you have to do so at runtime.

https://github.com/docker-library/mysql/issues/422#issuecomment-386967535
The error message is directly from the OS, not something we can change in the image

https://github.com/docker-library/mysql/issues/303#issuecomment-327126327
You would want to configure Docker's seccomp profile

**Comment by tianon** [comment] 2021-07-19 23:13
Closing as a duplicate of #303 -- if you want this logging changed, that change will have to happen in MySQL itself.

**Closed by tianon** 2021-07-19 23:13 UTC
Labels: question
