### ISSUE TITLE
mysqlbinlog binary is missing on docker image 8.0.30

### ISSUE THREAD

**Issue by byjg** [docker-library/mysql#903] opened 2022-08-03 18:15 UTC
I am using the image `mysql:8.0.30`, and I noticed that several MySQL binaries are missing in that image including the `mysqlbinlog`. 

Some of the binaries are missing from `8.0.30`, but they exist on `8.0.28`:

- myisam_ftdump
- myisamchk
- myisamlog
- myisampack
- **mysqlbinlog**
- mysqlcheck

Is that planned? If yes, what are the alternatives?

**Comment by tianon** [comment] 2022-08-03 19:25
This is effectively a duplicate of #847 :grimacing: (cc @ltangvald :eyes:)

If you require these commands, I would suggest switching back to the Debian-based variants for now. :+1:

**Closed** 2022-08-09 00:19 UTC
