### ISSUE TITLE
Warning unable to load '/usr/share/zoneinfo/*' as time zone. Skipping it.

### ISSUE THREAD

**Issue by koby-meir** [docker-library/mysql#229] opened 2016-10-26 12:31 UTC
I'm running the following docker configuration:

```
devmysql:
image: mysql
hostname: mysql
environment:
    - MYSQL_ROOT_PASSWORD=super_secret_password
    - MYSQL_DATABASE=db_user
    ports:
    - "127.0.0.1:3306:3306"
```

And i'm getting the following warning messages:

```
Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
```

Is there a way to do load the timezone information without showing these warnings?

**Comment by strarsis** [comment] 2016-12-02 21:10
Apparently this can be fixed by installing the tzdata package:
````
FROM mariadb:10.1

RUN apt-get update \
 && apt-get install --no-install-recommends -y tzdata \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*
````
Using this image instead results in the warning not being logged anymore.

**Comment by AndyBowes** [comment] 2017-11-07 15:36
I have encountered the same issue when attempting to set the MySQL timezone as UTC on our image.
- timezone=+0:00
- default-time-zone=+0:00

Is this issue likely to be fixed for a 5.7 image as I'd rather not create & extend our own mysql docker image.  Other that the slight increase in the image size, is there any other reason not to install tzdata as part of the standard image?

**Comment by tianon** [comment] 2017-11-08 04:50
The `tzdata` package is already included in the images -- the warnings described in the OP are harmless (and simply refer to files that aren't timezones that MySQL is thus appropriately ignoring):
```console
$ docker pull mysql:5.7
5.7: Pulling from library/mysql
Digest: sha256:1a2f9361228e9b10b4c77a651b460828514845dc7ac51735b919c2c4aec864b7
Status: Image is up to date for mysql:5.7

$ docker run --rm mysql:5.7 dpkg -l | grep tzdata
ii  tzdata                    2017b-0+deb8u1           all          time zone and daylight-saving time data
```

Is there actual harm being caused by these warnings?  A simple reproducer for issues with MySQL using timezones properly would be appreciated for digging further.

**Comment by tianon** [comment] 2017-12-26 23:20
Closing given lack of additional information for reproduction.

**Closed by tianon** 2017-12-26 23:20 UTC

**Comment by boay24** [comment] 2020-03-14 13:49
2020 i confirmed this  problem still persists.
![image](https://user-images.githubusercontent.com/61148495/76683219-f9975b00-6634-11ea-8961-35c6ef40ada8.png)

**Comment by tianon** [comment] 2020-03-14 15:43
> Is there actual harm being caused by these warnings?

**Comment by someonewithpc** [comment] 2020-04-27 20:45
@tianon I think so:

```
MariaDB [(none)]> select convert_tz(now(), 'UTC', 'CET');
+---------------------------------+
| convert_tz(now(), 'UTC', 'CET') |
+---------------------------------+
| NULL                            |
+---------------------------------+
```

This seems to suggest that all timezone related operations are broken.

**Comment by tianon** [comment] 2020-04-27 20:48
@someonewithpc I think the underlying cause of your issue is not these warnings:

```console
$ docker pull mariadb:10.4
10.4: Pulling from library/mariadb
Digest: sha256:379f3689cfcd53fd561c1aa2aea0a336a2362c9d31306528228321344a9cf979
Status: Image is up to date for mariadb:10.4
docker.io/library/mariadb:10.4

$ docker run -dit -e MYSQL_ROOT_PASSWORD=example --name test mariadb:10.4
bf0814561d25bbd45704b89a704dc370a8be5eecd45998d30d7e42260d4cd73d

$ docker logs test | grep -i zone
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.

$ docker logs --tail=2 test
2020-04-27 20:46:45 0 [Note] mysqld: ready for connections.
Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

$ docker exec -i test mysql -uroot -pexample <<<'select convert_tz(now(), "UTC", "CET")'
convert_tz(now(), "UTC", "CET")
2020-04-27 22:47:57
```

**Comment by someonewithpc** [comment] 2020-04-27 21:08
@tianon Hm, yeah, your steps work for me too. Sorry for the false alarm. It seems I had an error in an entrypoint script. 

However, with `docker-compose`, even though I specify `MYSQL_ROOT_PASSWORD=foobar` in the environment, I still get the prompt saying I need to add a password to the root user. It's just a mild annoyance, much like this, it seems, though.

**Comment by ctrlbrk42** [comment] 2020-05-30 22:14
I use this code on several docker build files, and it works well for me:

```
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "US/Eastern" | tee /etc/timezone && \
    dpkg-reconfigure tzdata && \
    cp /usr/share/zoneinfo/US/Eastern /etc/localtime
```
I can confirm that at least with the mariadb:10.4 tag, tzdata is already pre-installed and just reconfiguring it like the above will solve the problem and eliminate the warning message.

**Comment by daryong** [comment] 2020-06-16 00:54
Thank you. Works fine for me.

**Dockerfile**
<pre>
FROM mariadb:10.5.3

RUN echo "Asia/Seoul" > /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
</pre>

**Comment by pratikgoud123** [comment] 2023-01-16 05:31
![image](https://user-images.githubusercontent.com/113279009/212605193-1607acce-d330-48a1-a046-ad20768a52f1.png)
