### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Markle-ddp** [docker-library/mysql#774] opened 2021-05-30 09:45 UTC

**Comment by wglambert** [comment] 2021-06-01 15:15
Arm isn't a supported architecture for MySQL https://github.com/docker-library/mysql/issues/318

**Comment by tianon** [comment] 2021-06-01 22:53
Closing as a duplicate of #318

**Closed by tianon** 2021-06-01 22:53 UTC
Labels: question
