### ISSUE TITLE
docker 安装mysql无法进入容器

### ISSUE THREAD

**Issue by ZdMirLong** [docker-library/mysql#434] opened 2018-05-29 13:34 UTC
centos上使用docker安装mysql,安装成功后log文件中没有生成随机密码.重新安装并使用-e设置密码后提示
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
这哪里有问题?

**Comment by wglambert** [comment] 2018-05-29 17:38
Could you post the commands you gave and the `docker-compose.yml` if you're using one

This thread seems related https://github.com/docker-library/mysql/issues/230

**Comment by ZdMirLong** [comment] 2018-05-30 00:51
我没有用 docker-compose.yml,我是这么安装的  
```

docker run -d -p 3306:3306 --name mysql01 -v=/usr/docker/mysql/config/my.cnf -v=/usr/docker/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456  mysql/mysql-server
```

下面是我的logs文件
```
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-29T13:06:42.075023Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
mbind: Operation not permitted
2018-05-29T13:06:42.476740Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2018-05-29T13:06:42.490377Z 0 [Warning] [MY-010315] [Server] 'user' entry 'healthchecker@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490428Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.infoschema@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490448Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490463Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490477Z 0 [Warning] [MY-010315] [Server] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490533Z 0 [Warning] [MY-010323] [Server] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490548Z 0 [Warning] [MY-010323] [Server] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.490570Z 0 [Warning] [MY-010311] [Server] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.495212Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.495236Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:06:42.502163Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.11'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
2018-05-29T13:28:04.919185Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-29T13:28:13.674249Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
mbind: Operation not permitted
2018-05-29T13:28:14.117929Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2018-05-29T13:28:14.131728Z 0 [Warning] [MY-010315] [Server] 'user' entry 'healthchecker@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131784Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.infoschema@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131804Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131819Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131833Z 0 [Warning] [MY-010315] [Server] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131868Z 0 [Warning] [MY-010323] [Server] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131881Z 0 [Warning] [MY-010323] [Server] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.131902Z 0 [Warning] [MY-010311] [Server] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.136449Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.136475Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-05-29T13:28:14.143397Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.11'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
```
以往在安装成功后应该会生成一个随机密码,但是在log文件中找不到密码,并且我`-e MYSQL_ROOT_PASSWORD=123456`这里设置的密码也进不去.
```
bash-4.2# mysql -uroot
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
bash-4.2# mysql -uroot -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
bash-4.2#

```

**Comment by wglambert** [comment] 2018-05-30 17:20
The volume you're mounting for `/var/lib/mysql` needs to be empty or contain the necessary files.
```console

$ docker run -d -p 3306:3306 --name mysql01 -v ~/my_cnf:/etc/my.cnf -v ~/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=12345 mysql/mysql-server
21c3cb94db92666ac8627098a2a7c2953719094a5ac5c6d69060988d0297d499
rei@Ayanami-clone:~$ docker exec -it mysql01 bash

# mysql -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.11 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

```console

$ ls ~/mysql
auto.cnf       ca-key.pem       ib_logfile1          private_key.pem
binlog.000001  ca.pem           ibtmp1               public_key.pem
binlog.000002  client-cert.pem  mysql/               server-cert.pem
binlog.000003  client-key.pem   mysql.ibd            server-key.pem
binlog.000004  ib_buffer_pool   mysql.sock=          sys/
binlog.000005  ibdata1          mysql.sock.lock      undo_001
binlog.index   ib_logfile0      performance_schema/  undo_002
```

**Comment by ZdMirLong** [comment] 2018-05-31 05:03
谢谢!按照您的方式安装成功,但是mysql服务无法启动
```

[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
[Entrypoint] No password option specified for new database.
[Entrypoint]   A random onetime password will be generated.
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
2018-05-31T04:51:14.928605Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.11) initializing of server in progress as process 19
[Entrypoint] Initializing database
mbind: Operation not permitted
2018-05-31T04:51:17.008943Z 5 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2018-05-31T04:51:18.573454Z 0 [System] [MY-013170] [Server] /usr/sbin/mysqld (mysqld 8.0.11) initializing of server has completed
[Entrypoint] Database initialized
2018-05-31T04:51:20.218758Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 65
2018-05-31T04:51:20.236703Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:20.237101Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:20.237792Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
2018-05-31T04:51:20.243379Z 0 [ERROR] [MY-010946] [Server] Failed to start mysqld daemon. Check mysqld error log.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:21.366908Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:21.369561Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:21.369601Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:21.370003Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:22.507789Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:22.510345Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:22.510383Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:22.510773Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:23.819465Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:23.822051Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:23.822087Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:23.822480Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:25.611886Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:25.614460Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:25.614496Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:25.614898Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:28.201899Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:28.204632Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:28.204682Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:28.205065Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:32.427592Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:32.430783Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:32.430845Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:32.431311Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:39.836113Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:39.838847Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:39.838886Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:39.839287Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
[Entrypoint] MySQL Docker Image 8.0.11-1.1.5
/dev/vda1 /etc/my.cnf xfs rw,relatime,attr2,inode64,noquota 0 0
[Entrypoint] Starting MySQL 8.0.11-1.1.5
2018-05-31T04:51:53.608886Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
2018-05-31T04:51:53.611523Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2018-05-31T04:51:53.611564Z 0 [ERROR] [MY-010119] [Server] Aborting
2018-05-31T04:51:53.611957Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.

```

**Comment by ZdMirLong** [comment] 2018-05-31 05:04
上诉错误我已经解决了  我在my.cnf中指定user=mysql 重新安装容器启动成功.非常感谢您的帮助!

**Comment by wglambert** [comment] 2018-05-31 16:38
Cool, closing since question is resolved.

**Closed by wglambert** 2018-05-31 16:38 UTC
Labels: question

**Comment by moocstudent** [comment] 2020-11-23 03:58
The problem is fixed , maybe U can try like this:
```
root@8bf9306c0338:/# mysql -uroot -p4iKSrfzoqdAmVPN5n7X3gPjNCQaNmiD1234G9Bctv9gW5vvd9ywOY
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 368
Server version: 8.0.16 MySQL Community Server - GPL

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

```
just using your password behind the '-p' and don't like show blew
```
root@8bf9306c0338:/# mysql -uroot -p
CHANGE NEWLINE INPUT PASSWORD MAYBE ERROR !
```

**Comment by yqchilde** [comment] 2021-02-08 08:21
其实这种方法并不是有效的，因为当前已经无法登陆，无论是否将password写出来都一样

**Comment by yqchilde** [comment] 2021-02-08 08:21
其实这种方法并不是有效的，因为当前已经无法登陆，无论是否将password写出来都一样

**Comment by yqchilde** [comment] 2021-02-08 08:22
> The problem is fixed , maybe U can try like this:
> 
> ```
> root@zhangqi:/# mysql -uroot -p4iKSrfzoqdAmVPN5n7X3gPjNCQaNmiD1234G9Bctv9gW5vvd9ywOY
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 368
> Server version: 8.0.16 MySQL Community Server - GPL
> 
> Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> 
> ```
> 
> just using your password behind the '-p' and don't like show blew
> 
> ```
> root@zhangqi:/# mysql -uroot -p
> CHANGE NEWLINE INPUT PASSWORD MAYBE ERROR !
> ```

其实这种方法并不是有效的，因为当前已经无法登陆，无论是否将password写出来都一样

**Comment by yqchilde** [comment] 2021-02-08 08:26
今天我也遇到了这个问题，记录一下解决方案：
1. 进入容器中
2. 使用命令 `/usr/bin/mysql_secure_installation` 
3. 按照提示进行密码初始化即可

**如下所示：**

```bash
# /usr/bin/mysql_secure_installation



NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MySQL to secure it, we'll need the current
password for the root user.  If you've just installed MySQL, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MySQL
root user without the proper authorisation.

You already have a root password set, so you can safely answer 'n'.

Change the root password? [Y/n] y
New password: 
Re-enter new password: 
Password updated successfully!
Reloading privilege tables..
 ... Success!


By default, a MySQL installation has an anonymous user, allowing anyone
to log into MySQL without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] n
 ... skipping.

By default, MySQL comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist
 ... Failed!  Not critical, keep moving...
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!




All done!  If you've completed all of the above steps, your MySQL
installation should now be secure.

Thanks for using MySQL!


Cleaning up...
# mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.50 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
