### ISSUE TITLE
Syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead. 

### ISSUE THREAD

**Issue by Eleanaortegagm** [docker-library/mysql#990] opened 2023-08-15 12:43 UTC
I cannot get rid of this warning and I tried to set global host cache size to 0 in a sql script.

**Comment by taco-chen** [comment] 2023-08-19 06:17
Also met this issue.

**Comment by StefaniOSApps** [comment] 2023-09-03 20:39
same

**Comment by rawr51919** [comment] 2023-10-23 12:28
Fixed in PR #1002

**Comment by LaurentGoderre** [comment] 2023-10-23 19:55
Duplicate of #921

**Closed by LaurentGoderre** 2023-10-23 19:55 UTC

**Comment by pushpa-01** [comment] 2024-05-23 11:10
I am facing error while running db container "The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead" where should I set it ?
Anyone has idea about it?

**Comment by LaurentGoderre** [comment] 2024-05-23 13:44
@pushpa-01 I believe this ios fixed in recent versions. If you can't upgrade to a new version yet, you can try to apply this change manually: https://github.com/docker-library/mysql/pull/1002/files
