### ISSUE TITLE
Mysql tag 5.7 switched from Debian to Oracle

### ISSUE THREAD

**Issue by lafokamotion** [docker-library/mysql#886] opened 2022-07-08 18:28 UTC
Messed up some permissions for files in a volume mount involved with one of my running pods.
Basically, I did some docker pulls on a few tags 5.7.38, 5.7, 5.7-debian, 5.7-oracle, and 5.7.37
followed by some docker inspects...

tag 5.7.38:  `"MYSQL_VERSION=5.7.38-1.el7"`
tag 5.7:      `"MYSQL_VERSION=5.7.38-1.el7"`
tag 5.7.37: `"MYSQL_VERSION=5.7.37-1debian10"`

I realize now there is a debian specific tag up there but I'll submit this for general awareness at the very least

**Comment by okorz001** [comment] 2022-07-08 23:35
This also happened with 8 starting with 8.0.29.

**Comment by wglambert** [comment] 2022-07-08 23:41
Duplicate of https://github.com/docker-library/mysql/issues/877

The the `:latest` tag changed from Debian Bullseye to Oracle Linux https://github.com/docker-library/mysql/pull/867
We don't have a great way of communicating changes to users outside of pull requests and commits in these repos, so to be aware of upcoming and past changes check out the PR's over at https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fmysql+is%3Aclosed

A good practice to use is a more specific tag that specifies the OS, and major.minor release numbers which are under "supported tags" https://hub.docker.com/_/mysql/

**Closed by wglambert** 2022-07-08 23:41 UTC
Labels: question
