### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Sniper30** [docker-library/mysql#838] opened 2022-04-01 13:46 UTC
i trying to run "docker pull mysql" in the terminal but it appears:
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by wglambert** [comment] 2022-04-01 15:16
This image doesn't support architectures other than amd64
MariaDB does have an arm64/v8 variant if you'd like https://hub.docker.com/_/mariadb?tab=tags

https://github.com/docker-library/mysql/issues/318#issuecomment-541534820
>My idea for this is to add support for rpm-based images since repo.mysql.com offers rpms for aarch64. This would only be for 8.0, though.

https://github.com/docker-library/mysql/issues/318#issuecomment-541592821
>8.0 was the first version upstream added official arm support for

Closing as duplicate of https://github.com/docker-library/mysql/issues/318

**Closed by wglambert** 2022-04-01 15:16 UTC
Labels: question

**Comment by tianon** [comment] 2022-04-01 16:32
If you switch to the `-oracle` variants (which we hope to make the default, eventually/soon!), they have `arm64v8` support. :+1:
