### ISSUE TITLE
Couldn't execute 'FLUSH TABLES': Access denied since 5.7.41/8.0.32

### ISSUE THREAD

**Issue by czende** [docker-library/mysql#941] opened 2023-01-26 15:43 UTC
Our mysql dump scripts stopped working because of updated `MYSQL_VERSION` ENV from `5.7.40-1debian10` to `5.7.41-1debian10` in Docker tag `5.7-debian`. (commits https://github.com/docker-library/mysql/commit/b3dc453ce1a149ad698e29715d818cf042605163 and https://github.com/docker-library/mysql/commit/77d590d7d141caa3280ff2d838f70c6581a9d704)

Bug is reported and confirmed here https://bugs.launchpad.net/ubuntu/+source/mysql-5.7/+bug/2003866

The only way how to fix this for now is downgrade to `5.7.40-debian` Docker tag.

**Comment by yosifkit** [comment] 2023-01-26 19:56
https://bugs.mysql.com/bug.php?id=109685 caused by the fix for https://bugs.mysql.com/bug.php?id=105761

A bug existing in upstream MySQL version `5.7.41` (and `8.0.32`) does not mean we'd move the `5.7` (or `8.0`) tags to an older release (unless upstream removes the broken releases). We'll have to wait for a new release or possibly documentation changes.

In the meantime, using the older image is a fine workaround. Or maybe the fix from the launchpad bug will work: "Granting RELOAD to the backup user restored previous dump behaviour"

**Comment by yosifkit** [comment] 2023-04-25 17:24
According to https://bugs.mysql.com/bug.php?id=109685, this is fixed in `5.7.42` and `8.0.33`

**Closed by yosifkit** 2023-04-25 17:24 UTC
