### ISSUE TITLE
Docker container IO performance

### ISSUE THREAD

**Issue by philiahe** [docker-library/mysql#456] opened 2018-07-23 07:58 UTC
With no CPU or memory restrictions, the configuration is exactly the same, with only half the performance of Host.

docker:
![image](https://user-images.githubusercontent.com/8486693/43064329-29fcbe7a-8e91-11e8-9e89-0767ea92cfe7.png)

host:
![image](https://user-images.githubusercontent.com/8486693/43064338-3060c9c8-8e91-11e8-9af6-7e50f0875cfd.png)

**Comment by tianon** [comment] 2018-07-23 14:01
Can you please provide more details about your install, setup, and testing
process for both environments?

How did you verify that the configuration is identical?

**Comment by philiahe** [comment] 2018-07-23 14:37
host all using Ubuntu 16.04.4 LTS.

mysql using mysql.5.7.22.

![image](https://user-images.githubusercontent.com/8486693/43083404-f8d46158-8ec8-11e8-9af4-7bdae7ba9053.png)

**Comment by tianon** [comment] 2018-07-30 21:13
Then IMO that's not really a fair test (you're not really comparing the exact same things).  Did you at least use the same upstream-supplied MySQL packages, or is that the `mysql-server` package provided by Ubuntu?

For this to be a fair test, it would need to start with the same version of Debian as the image (Stretch, currently), and install the same packages, applying the same configuration changes.  Additionally, it would be prudent to ensure the exact same type of volume is used to minimize performance differences.  Ideally, it'd be tested on the same VM with the same volume (cleaned between tests), to help minimize variables further.

As it stands, the configuration this image provides is almost 100% the stock configuration provided by Oracle's upstream MySQL packages.  The only changes we make are minor (logging, bind address, reverse DNS resolution).  Given this, I have a hard time believing there's a performance disparity, but even if there is, there's not really much we could do in the image to overcome it since it would likely be an issue with Docker or with the Linux kernel itself.

**Comment by tianon** [comment] 2018-07-30 21:14
For reference, https://github.com/docker-library/mysql/blob/075c24deda2f551531c76ef46283c8c9c810d78f/5.7/Dockerfile is the exact current `Dockerfile` which corresponds to the current `mysql:5.7` image, and would be an appropriate guide for setting up a comparable system for testing non-Docker performance in a way that can be directly and fairly compared to the Docker performance.

**Comment by philiahe** [comment] 2018-07-30 21:27
In fact, all my tests are in the same environment, including the volume. and I've shown above that I'm using the same Mysql version, the same configuration.

So, I can't understand why the performance is so wasted, what other configuration might be required?

Thank you for your reply:D

**Comment by tianon** [comment] 2018-08-20 23:10
Given that your host is Ubuntu, there's already some variance.  Was the package you installed from https://dev.mysql.com/downloads/repo/apt/, or was it from Ubuntu's repos?

To really give it a fair test, it ought to be fully identical host to container as far as setup and configuration are concerned, which means Debian 9 (https://github.com/docker-library/mysql/blob/b39f1e5e4ec82dc8039cecc91dbf34f6c9ae5fb0/5.7/Dockerfile#L1), installing from Oracle's packages (https://github.com/docker-library/mysql/blob/b39f1e5e4ec82dc8039cecc91dbf34f6c9ae5fb0/5.7/Dockerfile#L51, https://dev.mysql.com/downloads/repo/apt/), etc.

If we can reproduce a performance issue that way, then it might be worth hitting up Oracle to see if they have any ideas as to what's causing the performance disparity.

**Comment by tianon** [comment] 2018-08-24 19:49
Given that there's not likely to be anything we've done in the image that could cause this disparity (it's either in the default MySQL configuration or an issue with Docker / the Linux kernel), I'm going to close this for now.  If there are things upstream recommends we change that could improve this, we'd love to consider them!

**Closed by tianon** 2018-08-24 19:49 UTC
Labels: Issue
