### ISSUE TITLE
Latest 5.7 container (5.7.14) seems to stopped working with custom user IDs anymore

### ISSUE THREAD

**Issue by ffdybuster** [docker-library/mysql#197] opened 2016-08-02 14:52 UTC
Having `/data/mysql` owned by 1000:1000, when I try to run:

```
docker run -d --name mysql -u 1000:1000 -p 3306:3306 -v /data/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=abcd mysql:5.7.14
```

results in `Initializing database` in the log output and instant termination without any further message. Replacing `5.7.14` by `5.7.13` results in a working MySQL instance.

When not specifying `-u 1000:1000` (and leaving `-v ...` away), it works fine.

**Comment by ltangvald** [comment] 2016-08-02 15:19
Could be a bug where something in 5.7.14 is returning a nonzero code (which will cause the entrypoint script to terminate).

**Comment by ltangvald** [comment] 2016-08-02 15:35
I tried mapping up /var/log/mysql to see if there was anything in the error log that would help, and that made it work...
The issue is probably that it can't write to the log file. Can you try also adding a -v somewhere:/var/log/mysql and see if that fixes it for you as well?

**Comment by ltangvald** [comment] 2016-08-02 15:36
We did a significant refactoring of the debian/ubuntu packaging for 5.7.14, so it's possible we no longer set the permissions for the log directory the exact same way

**Comment by ffdybuster** [comment] 2016-08-03 06:31
Yes, mapping /var/log/mysql to something the user can write to fixes the problem. Thanks a lot!

**Comment by ltangvald** [comment] 2016-08-03 07:40
Great!
Both 5.7.13 and 5.7.14 will fail without printing an error if the log directory isn't writeable, but from what I can see they both set the directory permissions the same. Will keep the issue open until we can find out why they behave differently.

**Comment by ltangvald** [comment] 2016-08-03 08:57
Found the cause: 5.7.14 changed the /etc/mysql structure to split up client and server config a bit more, and this breaks the config modifications done in Dockerfile. One of the modifications was to make the server log to stdout instead of /var/log :)

I'll make an update for it.

**Comment by ffdybuster** [comment] 2016-08-03 10:01
Cool! Thanks for fixing this :)

**Comment by tianon** [comment] 2017-12-26 23:16
Fixed in https://github.com/docker-library/mysql/pull/199. :+1:

**Closed by tianon** 2017-12-26 23:16 UTC
