### ISSUE TITLE
How to run a script every started?

### ISSUE THREAD

**Issue by zhangguanzhang** [docker-library/mysql#786] opened 2021-09-06 09:12 UTC
There are inexplicable permissions problems in some environments. I want to execute chown before the mysqld process to fix these problems.   How could I use the root user to run the script, :
```
chown -R mysql:mysql /var/log/mysql  /var/run/mysql /var/lib/mysql
chmod 1777 /tmp
```

**Comment by zhangguanzhang** [comment] 2021-09-06 09:31
something like this https://github.com/MariaDB/mariadb-docker/issues/284#issue-550132097
But I dont't want to hijack the `docker-entrypoint.sh`

**Comment by tianon** [comment] 2021-09-07 19:49
Duplicate of #642

**Closed by tianon** 2021-09-07 19:49 UTC

**Comment by zhangguanzhang** [comment] 2021-09-08 01:36
not Duplicate.  the scripts in `/docker-entrypoint-initdb.d/` cannot use `gosu root` to run a command

**Comment by yosifkit** [comment] 2021-09-08 16:29
`gosu` can only be used to drop *from* root to another user; not to go from an arbitrary user up *to* root.

**Comment by tianon** [comment] 2021-09-08 16:39
If you want to run the startup scripts as root, you'll need to implement your own entrypoint.

**Comment by zhangguanzhang** [comment] 2021-09-09 01:52
> If you want to run the startup scripts as root, you'll need to implement your own entrypoint.

I think the script should change to this:
```
		if [ "$(id -u)" = "0" ]; then
			mysql_note "Switching to dedicated user 'mysql'"
                        docker_process_init_files /docker-entrypoint-root-run.d/*
			exec gosu mysql "$BASH_SOURCE" "$@"
		fi
```
