### ISSUE TITLE
mysql_config_editor missing

### ISSUE THREAD

**Issue by koppenho** [docker-library/mysql#966] opened 2023-04-14 03:31 UTC
Current image "latest" (alias "oracle") for linux/amd64 is missing tool `mysql_config_editor`.

However the image contains the binary
`/usr/bin/mysql-secret-store-login-path`
which seems to be useless without the  `mysql_config_editor`.
```
$ /usr/bin/mysql-secret-store-login-path --help
Failed to execute "mysql_config_editor", make sure it is installed and available in the PATH environment variable. Internal error: Process "mysql_config_editor" finished with exit code 128: mysql_config_editor could not be executed: No such file or directory (errno 2)
```
From this I conclude that `mysql_config_editor` was unintentionally dropped.
I recommend to add this tool.

In other images (e.g. "debian") the tool  `mysql_config_editor` is included.

**Comment by yosifkit** [comment] 2023-04-14 21:36
Related/duplicate of https://github.com/docker-library/mysql/issues/847

**Closed** 2023-04-14 21:37 UTC

**Comment by jedwards1211** [comment] 2024-10-06 03:01
@yosifkit `mysql_config_editor` is missing from the `debian` images too, so not a duplicate of that issue
