### ISSUE TITLE
Where is the mysql5.7 configuration file？

### ISSUE THREAD

**Issue by bkingalex** [docker-library/mysql#622] opened 2020-01-06 04:00 UTC
I pull the mirror image of mysql 5.7.
Mysql configuration file could not be found after running the image.
The /etc/mysql directory is empty.
I wonder where the configuration file is

**Comment by wglambert** [comment] 2020-01-06 17:36
https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file
>The default configuration for MySQL can be found in /etc/mysql/my.cnf

From my running mysql containers
```console
$ docker ps | grep -i mysql
75c91f127476        mysql:5.7              "docker-entrypoint.s…"   3 days ago          Up 3 days           3306/tcp, 33060/tcp    wordpress_db_1
4427a399ac79        mysql:5.7              "docker-entrypoint.s…"   3 days ago          Up 3 days           3306/tcp, 33060/tcp    ghost_db_1
5d951f5725c6        db39680b63ac           "docker-entrypoint.s…"   3 days ago          Up 3 days                                  k8s_mysql_mysql-5b59c4cd99-6d9d5_default_ddcd0cc2-1873-4f36-9161-0db8916c08a1_1

$ docker exec 75c91f127476 ls /etc/mysql
conf.d
my.cnf
my.cnf.fallback
mysql.cnf
mysql.conf.d

$ docker exec 4427a399ac79 ls /etc/mysql
conf.d
my.cnf
my.cnf.fallback
mysql.cnf
mysql.conf.d

$ docker exec 5d951f5725c6 ls /etc/mysql
conf.d
my.cnf
my.cnf.fallback
mysql.cnf
mysql.conf.d
```

With a new container
```console
$ docker run -d --rm --name test -e MYSQL_ROOT_PASSWORD=root mysql:5.7
e84c25a3a3ebeca30789adfc5b8700fe4152592b9a859d2bc1c4eac44472d60e

$ docker exec test ls /etc/mysql
conf.d
my.cnf
my.cnf.fallback
mysql.cnf
mysql.conf.d
```

**Comment by wglambert** [comment] 2020-01-10 13:05
Closing since I wasn't able to reproduce the issue

**Closed by wglambert** 2020-01-10 13:05 UTC
Labels: question
